[theme]
base="dark"
primaryColor="#E50914"
backgroundColor="#000000"
secondaryBackgroundColor="#141414"
textColor="#FFFFFF"
font="sans serif"

[light]
base="light"
primaryColor="#E50914"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#FAFAFA"
textColor="#1A1A1A"
font="sans serif"
